Some fixes for the ODBC binding.
Branches: main

Some fixes for the ODBC binding.

extras/odbc/odbc.m:
	Fix a compilation error: s/String/MR_String/ - the former no longer
	exists.

	Many things that were declared with static linkage in this module
	can actually be referred to by from other object files if
	--intermodule-optimisation is enabled and a foreign_proc referring
	to them is inlined across module boundaries.  Change the linkage
	to external in places where this can happen.

	Add a feature set pragma that requires conservative GC; the error
	message for this is more friendly than when the C code finally
	fails to compile.