Don't link to libmer_eventspec redundantly.
This avoid a link error when using clang's ThinLTO mode:
    error: Failed to link module
    ../trace/libmer_eventspec.a.llvm.18688.mercury_event_parser.c:
    Expected at most one ThinLTO module per bitcode file

compiler/Mmakefile:
    Remove libmer_eventspec.a from MLOBJS.
    Mmake.workspace already causes the library to be linked in.