Bootstrap the none.gc.debug grade using MSVC as the C compiler.
Estimated hours taken: 2

Bootstrap the none.gc.debug grade using MSVC as the C compiler.

compiler/c_util.m:
	Avoid a limitation in MSVC where string literals are not allowed
	to be longer then 2048 chars.
	Error C2026 is now avoided by instead of outputing a string as
	"a very long string" chunk it up into "a very " "long string"
	where each chunk is 512 characters long.
	Redefine c_util__output_quoted_string to call
	c_util__output_quoted_multi_string, so as to avoid some code
	duplication.

compiler/llds_out.m:
	The definitions of any types used in the module need to be
	output before they are used, so output them first.