Improve an error message for type class method declarations.
Currently, if a type class method declaration is incorrectly started with ":-",
we print the following error:

     Error: `:-' is not a valid declaration type.

This is a bit mysterious since in nearly every other context in Mercury, ":-"
is exactly how you begin a declaration. Change the parser to check for ":-"
at the beginning of type class method declaration and print an error specific
to that situation.

compiler/parse_item.m:
     As above.

tests/invalid_nodepend/Mmakefile:
tests/invalid_nodepend/bad_method_start.{m,err_exp}:
    Add a test for the new error message.