Improve the wording of some error messages.
Use the word "corresponding" instead of "preceding" in error messages like:

    Error: clause for predicate `foo'/0 without preceding `:- pred'
    declaration.

The language imposes no ordering on declarations so there is no sense in which
the `:- pred' declaration has to precede the clause.  This is doubly true for
`:- typeclass' and `:- instance' declarations, which may also occur in
different source files from each other.

compiler/make_hlds_error.m:
compiler/add_class.m:
	Make the above change.

	Delete a comment regarding this issue.

tests/invalid/*/.err_exp:
	Update expected error outputs.