Fix references to ssdb_hooks in C# grades.
The Mono compiler started giving me these errors for references to the
`ssdb_hooks' global from other modules:

Mercury/opts/exception.opt(365,15): error CS0103:
The name `ssdb_hooks' does not exist in the current context

library/exception.m:
	Qualify references to `ssdb_hooks' symbol.